### PR TITLE
[Ulica] Lots of items and two overlay by Maia/kween-kobold and watches by AliK/Ali-Anomma plus two fixes

### PR DESCRIPTION
**Pull request by hoasd1**
#### Summary

Adds bunch of items and two overlay by Maia/kween-kobold and item variant of watches by AliK
#### Content of the change

By Maia/kween-kobold :

Items :

- Medical gauze
- Foil wrapper
- Throwing axe
- Bone marrow
- Mutant bone marrow
- Tainted bone marrow
- Roasted bone marrow
- Cinnamon
- Cornmeal
- Alcohol wipes
- Snack cardboard box
- Dry dog food
- Dried beans
- Dried lentils
- Raw lentils
- Powdered gelatin
- Maple syrup candy
- Nut and bolt
- Italian seasoning
- Badminton shuttlecock
- Splatter guard
- Toilet paper
- Vaccum sealer
- Vibrator
- Black tea leaf
- Green tea leaf
- Tree spile
- Pepper
- Sandbox kit
- Human skull

Overlay :

- Throwing axe with both gender variants

By AliK :

Items :

- Silver watch
- Game watch
- Platinum watch
- Gold watch
- Fancy watch
- Diver's watch

Added JSONs to Dry dog food , bone marrow , mutant bone marrow and cornmeal to fill the similar
objects of them

Added JSON to wall wiring to fix the problem of it doesn't have his sprite ( Sorry about that by the way )

Changed not existing ID written in Windows JSON to existing one ( Wrong written Alarm taped window )

#### Testing

for_the_items
nice_watches
fixed_sorry
Additional_stuff

#### Additional information

Who knows player feedback about missing sprites could lead to fixing other things ( The wall wiring )

### CODE REVIEW

**Comment by Fris0uman** [comment]
You're missing credits for AliK

**Comment by hoasd1** [comment]
That's intentional because I can't find AliK's Github account...
Well I will tell him through Discord 👍

**Comment by Fris0uman** [comment]
> I can't find AliK's Github account
If you don't have a github account to put coauthors you need to add a credits.txt file in a folder with the sprite and put the name of the crontributor in the file. You can look in the repo for a bunch of exemples of that

**Comment by hoasd1** [comment]
Got the Github account of AliK ( AliK told me about it in the CDDA Tilesets Discord server )

Sorry about forgetting the reason why I wasn't including credits text anymore so I gone to add a credits text file to bag_garbage folder because Sinister don't have any ( Told me through Discord DMs and is the one who did such recolored sprite ) 👍

**Pull request merged**
