### PR TITLE
Ultica "ventilation shutter, rails by me, bagpipes by Aoae"

### PR DESCRIPTION
**Pull request by int-ua**
#### Summary
Ultica "ventilation shutter, rails by me, bagpipes by Aoae"

#### Content of the change
t_metal_ventilation_shutter_1_4x
bagpipes_4x
t_railroad_track_multitile_4x

### CODE REVIEW

**Comment by acepleiades** [comment]
test
The rails should use gravel center instead of unconnected
And bagpipes lack outline but it's not a big issue

**Comment by int-ua** [comment]
I see black pixels under the bagpipes, are you sure they lack the underline?

**Comment by int-ua** [comment]
We are halfway there
Screenshot_20210727_203500

**Comment by int-ua** [comment]
Screenshot_20210727_214746
good enough for now IM**H**O

**Pull request merged**
