### PR TITLE
[Ultica] Item sprites for mutagen samples

### PR DESCRIPTION
**Pull request by HenryWong327**
#### Summary
Added item sprites for all mutagen samples currently in the game.

#### Content of the change
Added unique sprites for the following:
- Slime
- Elf-A
- Alpha
- Snail
- Insect
- Plant
- Trog
- Spider
- Human

The rest share 5 generic sprites namely:
- Flesh
- Flesh + fur
- Flesh + bone
- Blood
- Bone

#### Testing
image

image

### CODE REVIEW

**Comment by Fris0uman** [comment]
How are the `Generic` sprites used? There's no json added by the PR and the files names are not valid item ids

**Comment by Fris0uman** [comment]
If the files themselves are not used in game put them there <https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/scratch/UltimateCataclysm/items> in the scratch folder

**Comment by HenryWong327** [comment]
> If the files themselves are not used in game put them there https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/scratch/UltimateCataclysm/items in the scratch folder

Ok I'll resubmit with that.

**Comment by Fris0uman** [comment]
you could just move the files around, no need to make a new PR

**Comment by HenryWong327** [comment]
> you could just move the files around, no need to make a new PR

I don't know how to do that. Oh well I've opened the new one already, it's not much of a bother.

**Pull request closed without merging**
