### PR TITLE
Remove duplicates

### PR DESCRIPTION
**Pull request by rafaelkb**
Added the 454 casing

asdasd

### CODE REVIEW

**Comment by Fris0uman** [comment]
Looks okay, but I wonder why it's failing the composition

**Comment by int-ua** [comment]
I don't see the 454 casing but otherwise looks ok.

**Comment by rafaelkb** [comment]
> I don't see the 454 casing but otherwise looks ok.

i removed it to be sure, ill upload it now

**Comment by int-ua** [comment]
Is it mentioned anywhere in JSON?

**Pull request merged**
