### PR TITLE
NeoDays "terrain fixes + qol vehicle tiles"

### PR DESCRIPTION
**Pull request by RepresentativeGear9**
#### Summary
NeoDays "a few vehicle tile additions/removals and terrain tile changes"

#### Content of the change

- Realistic doors - hddoors, doors, opaque, sliding - for vehicles,
- Windshield revamp and recolor,
- Better look for seats,
- Border around water tiles for clarity and recolor for darker feel,
- Lowered grass tile saturation,
- Darker vehicle/hd vehicle parts, i.e boards/stowboards,
- Removed bright second floor open air tile,
- Lowered saturation of pavement tiles and recolor,
- Replaced sidewalk tiles with concrete tiles for nicer appearance,
- Edited trunk door, trunk door open, and floor trunk tiles

#### Testing
https://imgur.com/a/hLotgS9

### CODE REVIEW

**Comment by int-ua** [comment]
Almost! Now only the `702_vp_seat_0` is unused and thus erroneously added as ID.

Please add "before" and "after" screenshots if you can.

And I will not be deciding on merging this as I'm not a maintainer of NeoDays, just helping you with GitHub.

**Comment by I-am-Erk** [comment]
If this is ready, I'll just need some screens and then I can merge

**Comment by Fris0uman** [comment]
What are all those sprite that are named 33xx.png? Sprites should be named with the in-game id of the thing they represent

**Comment by Fris0uman** [comment]
7 months later of not finding time to review this, I can confidently say that this PR is too big to be easily reviewable. Could you please cut it in smaller chunks and re submit it?

**Comment by Fris0uman** [comment]
Closing as stale, feel free to resubmit it in smaller chunks

**Pull request closed without merging**
