### PR TITLE
[Ultica] variants added to sludge

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Ultica "added variants to fd_sludge"

#### Content of the change
added two more variants to fd_sludge multitile, changed .json

#### Testing
image

### CODE REVIEW

**Comment by int-ua** [comment]
Looks like these changes were accidental, no?

armor

**Comment by int-ua** [comment]
Oh, you've created a PR to merge the `master` branch of your fork into the upstream (this repository) `master`. It's a bit problematic as it will create commits in the upstream that will need to be merged back into your fork `master`. It's much easier to create "feature branches" for PRs and keep the `master` branch exclusively for syncing with upstream. Please ask more about them at Discord

**Comment by int-ua** [comment]
But the sludge looks good, looking forward to seeing it in the game

**Comment by int-ua** [comment]
I think this video by @acepleiades includes the part about creating feature branches https://www.youtube.com/watch?v=cF3qIWt6ZEw

**Comment by acepleiades** [comment]
Excellent sludge, but yeah what is the rm armor commit?

**Pull request closed without merging**
