### PR TITLE
[NeoDays] Adds missing Bright Nights medical zombies

### PR DESCRIPTION
**Pull request by twtw3000**
#### Summary
Adds some missing Bright Nights medical zombie tiles

#### Content of the change

Adds
zombie nurse tile       mon_zombie_nurse.png
zombie surgeon tile     mon_zombie_surgeon.png
zombie vivisector tile  mon_zombie_vivisector.png
to pngs_tiles_10x10/monsters/zombie/mon_zombie_medical/

#### Testing
Before
bnmedzombiesbefore
After
bnmedzombiesafter

### CODE REVIEW

**Comment by Golfavel** [comment]
Could you move these additions to instead be under ``/pngs_tiles_10x10/mod/bn/monsters/zombie/``?

**Comment by twtw3000** [comment]
Sorry about that.  I hope this corrects the issue.

**Comment by I-am-Erk** [comment]
I don't mean to be rude, but bright nights can maintain their own tilesets, we're not doing it for them

**Comment by twtw3000** [comment]
No offense taken.  It was my fault.  I shouldn't have just assumed this included the fork as well.

**Pull request closed without merging**
