### PR TITLE
Update Credit.txt of MSX

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary
MSX "Update credit.txt of MSX"

#### Content of the change

Credits file of MSX was missing a contributor listed. Literally my first contribution to DDA was https://github.com/CleverRaven/Cataclysm-DDA/pull/11707, which was when the Mshock set was developed into MShock Modded, which was used as the base by Xotto (source: https://discourse.cataclysmdda.org/t/20170216-big-sprite-update-mshock32xottoplus-tileset-oversprite-tileset/11301).

#### Testing

N/A

### CODE REVIEW

**Comment by Fris0uman** [comment]
What sprite did you add? We can maybe give credit directly for those sprites

**Comment by Fris0uman** [comment]
Since you're here it would be very helpful if you could actually identify your contributions, it would allow for a nicer tracking of the credits.

**Comment by I-am-Erk** [comment]
CV, we'd be more than happy to credit you. It is kind of the main reason we started this project. You don't need to dramatically complain in other communities about it, Fris0 is trying to help you get the same type of direct credit every other artist enjoys in the project, instead of a vague wave towards "I guess CV did some stuff but nobody knows what". It's meant to be respectful, not hostile.

**Comment by chaosvolt** [comment]
If I can find time I can try to look through later on, thank you.

**Comment by chaosvolt** [comment]
PR linked does not actually include the change this PR added.

**Comment by Fris0uman** [comment]
It links to the whole history of the tileset when it lived in the dda repo, therefor it does give credit to anyone that PRed something to that tileset at the time.

**Comment by I-am-Erk** [comment]
It includes all the PRs you just linked, with your name and specific contributions.

https://github.com/CleverRaven/Cataclysm-DDA/commits/60ff294b9613ae6cddcb250e84f7e66921e5f3ad?after=60ff294b9613ae6cddcb250e84f7e66921e5f3ad+244&branch=60ff294b9613ae6cddcb250e84f7e66921e5f3ad&path%5B%5D=gfx&qualified_name=60ff294b9613ae6cddcb250e84f7e66921e5f3ad eg

It's what we likely should have been doing in the first place as it gives much better credit information.

**Comment by chaosvolt** [comment]
Guess that works then.

**Pull request closed without merging**
