### PR TITLE
Ultica "32x48 tilesheet"

### PR DESCRIPTION
**Pull request by int-ua**
#### Summary
Ultica "32x48 tilesheet"

#### Content of the change
Moved part of the tall tilesheet into a new 32x48 tilesheet.

Removed the `incomplete_tall` sheet as I don't see the point of having it anymore, there were just a couple of sprites there left after the move, they were of good enough quality to go into the `tall` sheet.

Some common backgrounds (shadows, ground, overmap field and water) moved into `common/` directories to be placed at the start of sheets and hopefully to make maintaining Chibi Ultica a bit easier in the future.

Corpses were not separated from the monster sprites yet.

### CODE REVIEW

**Comment by int-ua** [comment]
@acepleiades please review the vehicle part move

@Fris0uman I'm figuring out what has to be updated in Chibi Ultica

**Comment by int-ua** [comment]
@I-am-Erk are you ok with removing the `incomplete_tall` sheet? There were no sprites left in it after the move

**Comment by Fris0uman** [comment]
image

Chibi Ultica doesn't have vehicle sprites anymore

**Comment by int-ua** [comment]
> Chibi Ultica doesn't have vehicle sprites anymore

Yes, most of them were moved to the new sheet. There are 5 subfolders in it:

* monsters
* overlay
* common
* vehicle
* character

**Comment by int-ua** [comment]
Ok, Chibi Ultica drives the `compose.py` changes. I will try to implement two new features.

* Option to ignore subdirectories
* Ability to read compose arguments from the `tile_info.json`

**Pull request merged**
