### PR TITLE
Testing Animations; Don't Merge this!

### PR DESCRIPTION
**Pull request by DillonSimeone**
Testing Zombie, Zombie Child and Zombie Fat.

#### Summary
MSX "animations tests for zombie, zombie child and fat zombie. Don't merge this!"

#### Content of the change

Adds three animations for three zombies, to see how it's like ingame. (And to get the dang tilesets composed)

#### Testing

See comment below with a video of the animations in action.

### CODE REVIEW

**Comment by DillonSimeone** [comment]
https://youtu.be/Ri7DJPpRQRU

Hmm, don't seem overwhelming as I expected.

**Comment by DillonSimeone** [comment]
Jabberwock animation doesn't work. Strange. Shows up as a static image instead of outright breaking.

**Comment by DillonSimeone** [comment]
Yep, gotta to dump everything inside that folder instead of keeping it clean with folders, it appears. Jabberwock animation works now.

**Comment by DillonSimeone** [comment]
Video of jadderwock and skeleton juggs in action... Blah.

https://www.youtube.com/watch?v=kOPFzovHnGw

*shakes fist at https://github.com/CleverRaven/Cataclysm-DDA/pull/46655 *

**Comment by int-ua** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.github/CONTRIBUTING.md#drafts ;)

**Comment by Fris0uman** [comment]
Closing to tidy up the PR cue a bit.

**Pull request closed without merging**
