### PR TITLE
[Ultica] Ferret and rabbit toy plushies by Dchieh/dchieh222

### PR DESCRIPTION
**Pull request by hoasd1**
#### Summary

Adds ferret and rabbit toy plush by Dchieh/dchieh222
#### Content of the change

Items :

- Ferret plushie
- Rabbit plushie

#### Testing
Plushies

#### Additional information

That's the first Ultica PR that added sprites to stuff included in the experimental versions after 0.G

### CODE REVIEW

**Comment by Fris0uman** [comment]
are they supposed to be this huge?

**Comment by hoasd1** [comment]
They aren't supposed to be this large but I wasn't sure if the contributor would be willing to put more effort into it.

Gonna tell him.

**Comment by hoasd1** [comment]
Ummmmm... >.>

Looks like the contributor will take days to respond if they will do it or not so what about drafting this PR until the respond arrives?

**Comment by Fris0uman** [comment]
Closing for now to tidy up, feel free to resubmit scaled down sprites later

**Pull request closed without merging**
