### PR TITLE
Revert "[Ultica] Fungal style overhaul by ShnitzelX2" 

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
Revert "[Ultica] Fungal style overhaul by ShnitzelX2"

#### Content of the change

Revert #2310 I was a bit careless in merging this one

### CODE REVIEW

**Comment by I-am-Erk** [comment]
There were some changes I think were good there, but the recolour was more of a personal taste thing I tihnk.

**Comment by Maleclypse** [comment]
> There were some changes I think were good there, but the recolour was more of a personal taste thing I tihnk.
Hey Erk, I've got no dog in this fight but I should mention that the only color description for any fungal entities or fungal zombies is blue.  So I think that's why they did a recolor, to match the description.

**Comment by ShnitzelX2** [comment]
My personal taste was limited: blue fungus was from in-game descriptions, pink spores were from the existing fine spore sprite to distinguish from green acid. From my submission on Discord:

> When I played my first couple runs, I found it odd that fungal creatures were described as having blue fungus but their sprites had red fungus, so I did some quick recolors (along with a handful of new sprites). My scheme was: gray body, neon-bluish fungus, pink spores. I think it helps make fungal creatures distinct and consistent. This is my first contribution; I don't know how well-received it is to edit existing sprites.

With this revert, the new sprites from #2311 also would need a recolor, unless fungal creatures are going to have variations in fungus color, in which case the game's monster descriptions should be edited.

I didn't expect the changes to go through in the first place, so it's fine. Let me know what (if anything) can be resubmitted.

**Comment by I-am-Erk** [comment]
That's a good answer thanks. The problem was that the neon recolour lost a lot of colour and shading depth. If you feel like redoing it I'd want a more natural shade that kept the original depth, and it would be a good idea to quote the description you're drawing from

**Comment by 1541Danny** [comment]
https://github.com/I-am-Erk/CDDA-Tilesets/pull/2349#issuecomment-2067775814

hoasd1 ones writeup includes the quotes from the fungal creature descriptions. Having a look in hitchhikers, I don't see any mention of the colour of the spores, but the _**blooming**_ things like the fungal blossom (and its giant vairant) mention the blue colour. Giant fungal wasp also gives a description of 

> Her abdomen glows faintly with a blue light, each pulse bringing a new crack for fungal growths to escape from

Personally I think the blue makes more sense thematically, as its very alien. I think when people think mushroom they think of those red and white cap mushrooms, and having the mycus be blue gives it this alien feel. I mean obiviously it already feels alien but the blueness gives it this "alternate" feel to it that my words are failing to describe. But you know, its yours and the artists call

**Pull request merged**
