### PR TITLE
Add new tileset, GiantDays

### PR DESCRIPTION
**Pull request by snw-0**
#### Summary
A new 20x20 tileset named **GiantDays**.  It is based on a 2x-upscaled NeoDays, but with all tiles redrawn or replaced to fit the new resolution.  It retains the lo-fi aesthetic of NeoDays and RetroDays, just... larger.
image

#### Content of the change
A full tileset, though it's incomplete; many tiles (particularly player character overlays) haven't been fixed or replaced and are therefore just upscaled copies of the NeoDays versions.  I've tracked my progress on [this Trello](https://trello.com/b/zTI71Ueg/giantdays).

#### Testing
Some screenshots:
Screenshot 2023-07-28 221906
Screenshot 2023-07-28 222319
Screenshot 2023-07-31 232948

#### Additional information
All the tiles currently included are either directly from NeoDays, modified versions thereof, or created by me.  It was suggested on Discord that I put up a PR in case anyone wishes to help complete the set.

### CODE REVIEW

**Comment by Maleclypse** [comment]
I love this.  Makes it much more readable to me and retro/neodays is one of my favorite tilesets.  Thank you and I look forward to seeing more of it!

**Comment by Fris0uman** [comment]
We need to keep track of authorship for our sprite, Neodays/Retrodays sprites are under cc by sa, so here we need to be able to look at a sprite in GiantDays and easily find the original sprite to be able to track authorship. So I think you'd have to do things in twosteps, first step copy original sprite here and make clear in the commit message where the sprite comes from, and then edit that sprite. Doing it thii way will creat a continuity in the commit history between this and the modified tileset

**Comment by snw-0** [comment]
So, if I understand correctly, you want me to:
- close this PR and delete the existing branch,
- create a new branch,
- make a commit that just copies the tiles from NeoDays, then
- copy my new tiles/jsons over them and make that a single commit?

**Comment by Fris0uman** [comment]
yes, a commit to copy and a commit to edit (copy over the work already done). Also because this is a lot of sprite you can do that in several smaller pull request, we don't have to get the whole tileset ready in one go

**Comment by snw-0** [comment]
See newer PR above.

**Pull request closed without merging**
