### PR TITLE
[Smap] some dirty changes to generic terrain

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Smap "some dirty changes to generic terrain"

#### Content of the change

color and shape changes for:
forest
river
swamp
trail
road

#### Testing

image
image

### CODE REVIEW

**Comment by int-ua** [comment]
The overall style of this tileset is matching pixels to map tiles but the roads in this PR are deviating from that style. I see you've tried to match topographic maps style of your country but is US they are a bit different and the game happens in US.

https://www.usgs.gov/programs/national-geospatial-program/us-topo-maps-america

example

example

**Comment by curstwist** [comment]
I think the water should use two tones since knowing the depth may be important to the player.  Thick forest could be more distinctive.

**Comment by int-ua** [comment]
```
road_nesw_manhole_old.png
road_old.png
```
are added as IDs by compose.py even though they are not used

**Comment by vetall812** [comment]
> ```
> road_nesw_manhole_old.png
> road_old.png
> ```
> 
> ~are added as IDs by compose.py even though they are not used~ wait, at least the first one is explicitly defined, are these correct?

Not sure, i have no such warnings when composing.

**Comment by vetall812** [comment]
Marked as draft, so it'll be merged just after all generated infrastructure.

**Comment by Fris0uman** [comment]
Is this ready to go?

**Pull request merged**
