### PR TITLE
[Ultica] New ammo sprites, batch 3 (final)

### PR DESCRIPTION
**Pull request by vetall812**
#### Summary
Ultica "New ammo sprites, batch 3"

#### Content of the change
Fixed 40x46mm grenades
Fixed 40x53mm grenades
Added 40x46mm hornets nest casings
Fixed 5.45x39mm
Fixed 5.7x28mm
Fixed 5x50mm
Fixed 7.62x25mm
Fixed 7.62x39mm
Fixed 7.62x51mm NATO
Fixed 7.62x54mm R
Fixed 84x246mm Carl Gustav's rockets
Fixed 8x40mm
Fixed 9x18mm
Fixed 9x19mm
Fixed .700 Nitro Express
Added 20ga (.62) ammo
Added blunderbuss ammo
Added cannon shot
Fixed H&K 12mm
Added hydrogen canister
Added flintlock ammo
Fixed M74
Added homemade rockets

#### Testing
image
image
image
image
image
image

### CODE REVIEW

**Comment by Faalagorn** [comment]
FYI: when it comes to 40 x 46 mm nades, there's one from Aftershock that is simply called "40mm EMP grenade"

**Comment by vetall812** [comment]
> FYI: when it comes to 40 x 46 mm nades, there's one from Aftershock that is simply called "40mm EMP grenade"

What's an ID for it? I'll add the sprite.

**Comment by Faalagorn** [comment]
Actually, it's from the Blaze Industries and obsolete for Aftershock, but it seems to be `40mm_emp`, though there seems to be an activated variant too: `40mmEMP_act`.

https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/BlazeIndustries/items/gun/grenade.json#L3
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Aftershock/items/obsolete.json#L475

**Comment by vetall812** [comment]
> Actually, it's from the Blaze Industries and obsolete for Aftershock, but it seems to be `40mm_emp`, though there seems to be an activated variant too: `40mmEMP_act`.
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/BlazeIndustries/items/gun/grenade.json#L3 https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Aftershock/items/obsolete.json#L475

Try this one.

**Pull request merged**
