### PR TITLE
Sprites for a number of tools and the bokken

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Ultica "Sprites for the bokken, acetelyne torch, UPS, locksmith kit, ice axe, geiger counter and hose"

#### Content of the change
Ice Axe: https://lospec.com/i/p5pr
Acetylene Torch: https://lospec.com/i/yprx
Hose: https://lospec.com/i/mgaj
Bokken: https://lospec.com/i/mwnz
UPS: https://lospec.com/i/htjj
locksmith kit: https://lospec.com/i/oe1h

#### Testing
image

### CODE REVIEW

**Comment by I-am-Erk** [comment]
These are good, but I would like to discuss a little tweaking on some of the shading here. Could you move the 32x32 sprites to the `incomplete` folder? The bokken and wielded version are fine, they can stay where they are.

**Comment by bombasticSlacks** [comment]
If you want to post here or in the discord what you would like changed I can just update them instead of adding more incomplete sprites

**Comment by bombasticSlacks** [comment]
image
alright updated the images after requests. I just removed the geiger counter for now

**Comment by bombasticSlacks** [comment]
actually sorry used the wrong hose

**Comment by bombasticSlacks** [comment]
image

**Pull request merged**
