### PR TITLE
Lab equipment by Wynnter, cottonwood by AliK

### PR DESCRIPTION
**Pull request by int-ua**
#### Summary
Ultica "Lab equipment by Wynnter, cottonwood by AliK"

#### Content of the change
out_4x

out

out

55gal_drum_4x

#### Testing
https://discord.com/channels/552510581161066497/552510581782085654/858863695102083084
зображення

### CODE REVIEW

**Comment by I-am-Erk** [comment]
What's with the file deletions?

**Comment by int-ua** [comment]
> What's with the file deletions?

    Warning: soap.png is already present in a non-filler sheet
    Warning: skipping filler for knife_combat
    Warning: skipping filler for knife_steak
    Warning: skipping filler for soap

**Comment by I-am-Erk** [comment]
t_tree_cottonwood_summer
t_tree_cottonwood_autumn
t_tree_cottonwood_spring
Here, you wanted some cottonwood. Alik can keep credit these are basic recolours.

**Comment by I-am-Erk** [comment]
t_tree_elm_autumn
t_tree_elm_spring
t_tree_elm_winter

t_tree_elm_summer

You can add these if you feel like it, otherwise I'll get to them later myself. I am not super happy with the leaves but they'll keep elm from looking like cottonwood in spring

**Pull request merged**
