### PR TITLE
fixed some compose.py duplicate warnings, vp fillers cleanup

### PR DESCRIPTION
**Pull request by int-ua**
May I suggest we move unused files out of the folders that are checked by the `compose.py`?

Unused files that were ignored:
```
t_wall_glass_edge_ew_4
t_wall_glass_edge_ew_3
t_wall_glass_edge_ew_2
t_wall_glass_edge_ew_1
t_scrap_wall_edge_ew_2
t_rock
t_moss
t_dirt_fg_rocks3
t_dirt_fg_rocks2
t_dirt_fg_rocks1
t_dirt_fg_grassrocks
t_dirt_fg_grass3
t_dirt_fg_grass2
t_dirt_fg_grass1
snow_shallow
snow_sparse_unconnected
snow_sparse_t_connection_w
snow_sparse_t_connection_s
snow_sparse_t_connection_n
snow_sparse_t_connection_e
snow_sparse_end_piece_w
snow_sparse_end_piece_s
snow_sparse_end_piece_n
snow_sparse_end_piece_e
snow_sparse_edge_ns
snow_sparse_edge_ew
snow_sparse_corner_sw
snow_sparse_corner_se
snow_sparse_corner_nw
snow_sparse_corner_ne
snow_sparse_center
line_target
cursor_red
cursor_green
cursor
shadow_32x32_mon_cat_kitten_walk
shadow_32x32_mon_cat
wheat_seedling
wheat_seed
wheat_mature
wheat_harvest
rose_seedling
rose_seed
rose_mature
rose_harvest
garlic_seedling
garlic_seed
garlic_mature
garlic_harvest
cabbage_seedling
cabbage_seed
cabbage_mature
cabbage_harvest
t_dirt_summer_tall
t_dirt_autumn_tall
snow_shallow_tall
leather_armor_helmet_f
soldier_filler
f_scrap_antenna
f_fridge
wheelbarrow_rotW
wheelbarrow_rotS
wheelbarrow_rotN
wheelbarrow_rotE
vp_seat_up_alt-incomplete
cart_handle_rotW
cart_handle_rotE
xlframe_vertical2
xlframe_horizontal2
hdframe_vertical2
hdframe_horizontal2
frame_vertical2
frame_horizontal2
vp_hddoor_right_open_rotE
vp_hddoor_opaque_right_open_rotE
vp_hddoor_opaque_right
vp_hddoor_opaque_left_open_rotE
vp_hddoor_opaque_left
vp_hddoor_left_open_rotE
vp_door_wood_right_rotS
vp_door_wood_right_rotN
vp_door_wood_right_open_rotN
vp_door_wood_left_rotS
vp_door_wood_left_rotN
vp_door_wood_left_open_rotN
vp_door_shutter_rotS
vp_door_right_open_rotE
vp_door_opaque_right_open_rotE
vp_door_opaque_left_open_rotE
vp_door_left_open_rotE
vp_door_R_open
vp_door_L_open
vp_wood_box_rotNS
vp_wood_box_rotEW
vp_hdhalfboard_vertical_2_right
vp_hdhalfboard_vertical_2_left
vp_woodhalfboard_vertical_t_right_rotN
vp_woodhalfboard_vertical_t_left_rotN
vp_woodhalfboard_vertical_right_rotN
vp_woodhalfboard_vertical_left_rotN
vp_woodhalfboard_vertical_2_right_rotN
vp_woodhalfboard_vertical_2_left_rotN
vp_woodhalfboard_sw_rotN
vp_woodhalfboard_se_rotN
vp_woodhalfboard_nw_rotN
vp_woodhalfboard_ne_rotN
vp_woodhalfboard_horizontal_rear_rotN
vp_woodhalfboard_horizontal_front_rotN
vp_woodhalfboard_horizontal_2_rear_rotN
vp_woodhalfboard_horizontal_2_front_rotN
vp_woodhalfboard_cover_rotN
vp_stowboard_horizontal_front_rotS
vp_stowboard_horizontal_front_rotN
vp_hdstowboard_horizontal_front_rotS
vp_hdstowboard_horizontal_front_rotN
t_card_generic
```

### CODE REVIEW

**Comment by I-am-Erk** [comment]
There's a few here I'm not sure why you're removing. What's up with those bottle item sprites for example?

**Comment by int-ua** [comment]
`gfx/UltimateCataclysm/pngs_small_20x20/items/tools/dining/bottle_glass.png` is the same as `gfx/UltimateCataclysm/pngs_small_20x20/items/containers/bottle_glass.png`. And the other two bottles are also there.

**Comment by int-ua** [comment]
I guess the changes are easier to view per-commit.

**Comment by int-ua** [comment]
`pngs_normal_32x32/monsters/animals/fish/corpse_mon_fish_medium.png` was present in a more recent contribution by ACEPLEIADES, looks similar but rotated.

`t_tree_peach.png` was a filler and has a proper sprite now.

`pngs_incomplete_32x32/terrain/t_railing/t_railing.png` was made into a proper autotile sprite set.

`mag_pistol` and `mag_smg` are IDs of books, not weapon magazines.

Other changes are self-explanatory it seems.

**Comment by int-ua** [comment]
Should I move the deleted files instead?

**Pull request merged**
