### PR TITLE
Revamp wall wiring and mollusk mutant

### PR DESCRIPTION
**Pull request by Holli-Git**
#### Summary

Felt these sprites could do a revamp
#### Content of the change
Redoes the shelled mutant, and changes the wall wiring to a lil lightning symbol

#### Testing
image

### CODE REVIEW

**Comment by Fris0uman** [comment]
What does the wall wiring look in game?

**Comment by Holli-Git** [comment]
> What does the wall wiring look like in game?

Look at the right wall, its the lil lightning symbol

**Comment by Fris0uman** [comment]
Damn it's super hard to see, no?

**Comment by Holli-Git** [comment]
That's on purpose, to be out of the way unless you're specifically looking for it. I can change it to be bigger if you'd like

**Comment by Holli-Git** [comment]
Oops misclick

**Comment by Fris0uman** [comment]
Make it stand out a little bit more I think, with an outline or a bigger icon

**Comment by Holli-Git** [comment]
image
Like this? Bigger?

**Comment by Holli-Git** [comment]
> Make it stand out a little bit more I think, with an outline or a bigger icon

image
Like this? Or should I make it bigger?

**Comment by Fris0uman** [comment]
Yep second one is good

**Pull request merged**
