### PR TITLE
[UltiCarto] Add new overmap tileset UltiCarto(grapher)

### PR DESCRIPTION
**Pull request by Inzarcon**
#### Summary

**[I have updated the attribution method along with further explanations, please see [my second comment below](https://github.com/I-am-Erk/CDDA-Tilesets/pull/2079#issuecomment-1657217983).]**

This adds the new overmap-only tileset _UltiCartographer_ (or short _UltiCarto_) I have been working on. It is currently in early alpha stage. The basic concept is to combine some ideas from several tilesets along with my own:
- _UltiCa_'s sprites and general style; I want the tileset to roughly capture what _UltiCa_ looks like in-game
- _SurveyorsMap_'s projection of actual in-game tinymaps
- _Larwick Overmap_'s color coding of some buildings such as shops
- _UndeadPeople_'s "image labels", again for shops and such (basic idea only, no actual UDP sprites/content used whatsoever)
- Overlapping roofs, shadows, trees etc. to create a pseudo-3D look
- Abusing the _fg/bg_ system to generate more sprite variants (for example 4 forest ground, 4 forest trees sprites for 16 possible variants)
- (A very specific workflow that may be borderline obsessive and will need its own documentation in case other people actually want to contribute to _Layer Hell_ \s)

#### Content of the change

- Regular core tileset files
- All sprites I've created so far, including their aseprite source files
- `templates` folder containing the source file for generic shops and a color palette of vanilla ascii colors and some I use as markers for planning. I can move this to the root `templates` folder if preferred
- `testing` folder containing a blender file for research on how shadows work and files for quick testing of more complicated sprites using the _Tiled_ app (https://www.mapeditor.org/)
- `downscale_library` folder to handle the attributions

#### Testing

Example view of the current tileset

Ran the composition after the migration and works fine in the game.

#### Additional information
- Sprite rotations are indexed by numbers instead of cardinal directions (for example `road_corner_0` instead of `road_corner_nw`) as I've found it slightly easier to work with if the json can just number them 0 to 3 every time. I can change this into the other naming convention if preferred
- This also causes the ordering of multitile spritesheets to be a bit different plus more sprites in general for the bigger spritesheets. I am using Aseprite slices instead of the python scripts for exporting the individual sprites anyway, but again I can match the ordering of at least the regular 4x4 grids if preferred
- As mentioned, if others are actually interested in contributing I can later add detailed documentation about my workflow and methodology
- While copying the original _UltiCa_ sprites for the credit commits I occasionally moved instead of copy-pasted them by accident. I should have caught all of them and the PR shows 0 deletions, though
- I saw some workflow yml files for the other tilesets; I haven't looked into that at all yet

### CODE REVIEW

**Comment by Fris0uman** [comment]
you don't need to keep the original ultica sprite, the idea is to have one properly labeled commit that copies the sprite and the subsequent commits that modifie the copy to get the desired result

**Comment by esotericist** [comment]
as the person who gave fris the advice in the first place, i'm going to try again to explain what the purpose of my suggestion was:

a commit (singular) that copies over the source files to *where they are going to go* (with their original filename) provides a clear moment in time of "these are copied from elsewhere in the repository". this doesn't transfer the history of those files, but it makes it easier to tell "this is what i need to be looking for elsewhere in the tree".

then you continue making changes to *those files* in *that location* so that any subsequent commits are clearly alterations descended from those files, and thus have a traceable history.

by putting all of the copies in their own bucket completely divorced from your actual work, you have broken all traceability of the history of where you're actually pulling from.

**Comment by Inzarcon** [comment]
I'm very sorry for my misunderstandings and commit mess then. And these exact issues you brought up are what I was trying to get at with my initial questions, but I probably still hadn't asked them clearly enough. Hence why I suggested creating a central library of the downscaled sprites, so that the link between original and modified sprites is clear, at least for all the currently existing sprites. 

To avoid further misunderstandings I'll to try my best to paraphrase your suggestions and my own:

1. I reset the commit mess and convert this PR into a draft for the time being.
2. I put all original sprite copies into a **singular** commit instead. (Commit 1)
3. I edit these original files, directly turning them into the downscaled spritesheets. (Commit 2)
4. I'm often creating several downscaled slices of one original sprite or combining elements of multiple original sprites. Should I
  - A: Create **one** intermediate commit for adding the original sprites of multitiles and such into one png file in the same folder? (Commit "1.5")
  - B: Add the combined pngs to the singular copy commit? (Commit 1)
  - B+: Also just add the resulting downscales to the same combined pngs in the next singular commit, so original sprites next to their downscaled counterparts? (Commit 2)
5. Once that link is established, I can remove any original sprites that may be left and not needed anymore.
6. I can now freely copy my downscaled edits to the individual main overmap files where they are actually used and combined.
7. Add the actual overmap sprite directories/files which are using the downscales (Commit 3)
8. Add the core tileset files (Commit 4)
9. Resubmit/update this Pull Request.
10. Should I keep the resulting library of downscales? This would also allow tracking further edits/updates of the downscales.
11. For future downscales I will use the same process, but try to fit all new/changed downscales for an overmap tile update into one commit respectively.

Do you approve this process or would you change something/add to it? What Format for the copy commit messages do you want me to use?

**Comment by Inzarcon** [comment]
Reopened for a second attempt at attribution history. Concerning the issue of separating the sprites from my actual work: To further clear things up I'll elaborate a bit more how this tileset works and where my questions/confusions come from, and also for new reviewers who don't know any of the context so far. I again apologize for creating another sort of wall (though this time explanatory), but don't want to leave much ambiguity (and can also use this for future documentation). If the tileset-internal sprite relations are not a problem, feel free to skip to the Attribution segment for a summary.

## The Process
Downscaling UltiCa's sprites itself is _not_ the point of this tileset, but an intermediate step. Most overmap sprites start with planning markers, which are later replaced by the downscaled UltiCa sprites with some overmap sprite specific tweaks:
<details>
    <summary>Image</summary>
    
</details>

#### Common Sprites
This single overmap sprite already combines downscaled versions/variations of 50+ original UltiCa sprites on its own. However, like in-game, a lot of these elements are shared with other overmap tiles, for instance this grocery shop. For this reason, it is more efficient to copy common sprites inbetween overmap spritesheets, often gathered to the sides:
<details>
    <summary>Image</summary>
    
</details>

### Further Tweaking and Combining
Usually these are all identical to the initial downscales, but some are further modified if necessary to make them fit with the rest of the respective overmap tilesheet, for example changing window colors for better contrast with the wall behind or resizing/rearranging them for symmetry. If that _specific or similar situation_ appears in another tilesheet, I reuse the edited version from the first. There are also cases like randomly generating new terrain sprites/segments from the downscaled variations, combining a downscale of one original tree with some of another's colors, or directly adding shading to trees instead of later to use them as random brushes due to their density in forest sprites:
<details>
    <summary>Images</summary>
    
    
    
</details>

### Templating
As of now, shops have a generic template which allows fast creation of basic variants and rotations. The sign and icons are separate layers, with the latter being mostly direct copies of original UltiCa-Sprites, aside from derivative batteries for electronics stores (part of the library below). The colored walls actually use the same white sprite (downscale of the original brick wall sprite, but desaturated), and can be dynamically set by a color overlay using the vanilla ASCII color palette:
<details>
    <summary>Image</summary>
    
</details>

## Attribution
To summarize, we now have downscaled sprites derived from the original UltiCa sprites, which are usually _not actually changed much_ after their initial downscaling, but serve as _templates/brushes_ for the main overmap sprites. These have a Many-to-Many relationship that can reach tripple digit numbers per final overmap sprite, though the vast majority of them are repeated duplicates, especially as the set of needed downscaled sprites approaches completion over time. And there are minor changes used only in and fitted to specific subsets of the overmap sprites, as well as random terrain generation and dynamic templating. Plus slicing up overmap tilesheets into the several single sprites used for tileset composition.

In theory, you could track every single such _intra-tileset_ relation, but this would quickly lead to reference spaghetti that outshines my previous commit wall blunder. **This is the core of my questions and misunderstandings:** _How granular do these relations need to be tracked?_

### Downscale Library
At this point my initially proposed central library comes in, which tries to formally merge the complicated sprite relationships with your suggestions. On its own, the tileset is figuratively isolated by a wall around it, so that not a single pixel from another place is allowed to be imported into it; changes can only happen by deriving internally from what is already there, be it existing downscaled UltiCa sprites, completely my own, or any possible hybrid on the spectrum inbetween.  To actually use _new_ downscaled UltiCa (or any other source's) sprites, they first have to pass through customs and border protection:

#### Copying
Like on my first attempt, the content embedded in the `downscale_library` is structured _exactly_ like the original `gfx/UltimateCataclysm/` directory in the repository; all original sprites used are mirrored to be located in the same subdirectories for direct validation. This was done for all used sprites so far in the first commit.

#### Creating the initial downscaled sprites
In the second commit, I added the downscaled versions of all original sprites to the same files. They are marked by a red border around them. The original sprites are kept as is; both for validation and to make it easier for potential contributors to tell which original sprite(s) the downscaled variants represent. See [the full list of comparisons of all sprite edits made in the second commit](https://github.com/Inzarcon/CDDA-Tilesets/commit/b79f785c14791631bd36b009cd5c49ae0719e639). There are a few different cases and resulting approaches to them:

##### Simple One-Sprite Downscaling
These mostly fit your recommendations, though they often use a larger canvas if there isn't enough transparent space left on the original sprite. 
imageimage

##### Multitiles and Merges
Lots of downscaled sprites and elements (usually those for terrain) are derived from several original sprites at once. Often, they are not intended to be direct counterparts to specific original sprites, but random brushes to represent all of them. In this case the first original sprite in the directory is used to merge them into one tilesheet, sorted alphabetically (potential future original additions appended). The other now redundant single-sprite files are then usually deleted if not needed anymore (in this second commit or later).
image

##### Further Edits
As explained above, some sprites have different variants/fixes for specific situations and are copied between the main overmap files when needed. I've added the major edits to the library to be sure until this aspect is clarified.
image

#### Library Status
All used sprites and their downscaled counterparts are part of the library. Future ones would be added using the same pipeline. Even though there may be further internal changes, by definition all sprites must ultimately originate from this one interface or myself. This now leaves the question: _Is this attribution method sufficient?_

**Comment by Fris0uman** [comment]
Every new sprite made of original cc by sa sprites must be able to be linked to every sprites used in its composition. So what you could do is for every sprite have in the same folder a table (see included file) with the file names of the sprites used to make it and links to their original in the repo, the links must point to the specific point in the commit history when you copied them
[credits.md](https://github.com/I-am-Erk/CDDA-Tilesets/files/12268026/credits.md)

**Comment by Inzarcon** [comment]
Alright, so I actually *do* have to track individual links after all.
1. By "every new sprite", do you mean every individual variant of a sprite or is their respective main aseprite tilesheet enough, given that the individual ones are just slices of it and otherwise identical in content?
2. If 1. applies, can I group sprites and their reference lines, even if there may be some references that don't actually appear in the final slices, but *are present* in the side collection of the tilesheet? For example grouping plants or floors and their references and copying the whole group into the side of the tilesheet/respective text file?
3. Should I also include a reference to the downscaled variants or is the library's mirrored file structure clear enough?
4. Anything else I need to change or is this the last obstacle?

**Comment by Fris0uman** [comment]
Every sprite needs proper attribution, but you can group if it's the same like for exemple you put one line in the table where file name is `field 1 to 5` and in the Link column you link to the things used to make the fields sprite. For the downscale folder you can do the commit history thing we discussed at the begining where the commit messages point to the original sprite.

**Comment by Fris0uman** [comment]
Aseprite sheets are not usefull for us, we need actual sprites for the scripts to build a tileset. 
 
 > pavement 1-4 of the original could be used in all road corners of my composed sprites,

 Then all composed sprites using them need to say so

> Also what exactly do you mean by commit message?

I went back to re-read what Eso said, disregard my comment  about commit message, the idea is to have a commit that copies the source without changing the filenames that way it's possible to know that the sprite has been copied from Ultica and what it was named to go look for the original in Ultica.

**Comment by Inzarcon** [comment]
> Aseprite sheets are not usefull for us, we need actual sprites for the scripts to build a tileset.

You're right, sorry. I meant the aseprite tilesheet files _**plus their respective exported png tilesheet versions.**_
> I went back to re-read what Eso said, disregard my comment about commit message

Thank you for clearing it up! _**Is the way I've set up the library ok then?**_ Like I explained above, I copied them in one commit, edited them in the second, and the file structure and names are an exact mirror of the original UltimateCataclysm directory. 

The one missing thing (for the library part) would then be linking to the specific original commit I copied from, which isn't too difficult though as I was using the same repository copy for everything. 
1. _**Is it enough to link to that commit's _UltimateCataclysm_ root folder**_ and refer to said mirrored file structure/edit commit history, especially for the ones I've merged as shown above? 
2. _**Or should I still additionally link all original -> copy sprite pairs in a text file?**_ (Not a big deal in this case as it only needs to be done once.)

> Then all composed sprites using them need to say so

And that is the main challenge here. For example, take these two forest floor variants:

image

While the sets of downscaled sprites are _mostly_ the same, there are some that only appear in one composition (zoomed examples above), but not in the other, meaning these specific markdown table entries need to be split up, **_so I will ultimately have to go through the entire list of 50+ downscaled sprites for _each_ individual overmap sprite_** anyway, in addition to the whole tilesheets. And again when I change something about an overmap sprite. Plus explaining all this to potential contributors and double checking if they are also doing it correctly. (Or is it ok for proper attribution if there are **_too many links that don't actually appear_** in a specific sprite?)

This would basically mean that managing the attributions will take a lot more time than working on the tileset itself, and I don't think this is very helpful for following the reference links either. Illustrated, even with just a few sprites considered the links already look like this:



And that is why I'm hoping that only uploading the whole tilesheets would also be a valid _and actually implementable_ way of doing it. What I mean by this in detail:
1. Upload the aseprite tile sheets along with their exported png counterpart sheets. **No single sprite pngs commited at all** (unless there only is one sprite to begin with).
2. Attribute these pairs using the markdown tables in the respective directories
3. Generate the single sprites **_locally during/before the composition pipeline_**. Would probably need to create custom derivates of the composing/slicing script(s) specifically for this tileset, but I wouldn't mind having to do that if it's fine for you.
4. Don't commit the generated slices either, only use them for local composition.
5. (Optional) **_If this is ok so far_**, can I now also group the downscaled sprites in single sprites and reference these? Or generally speaking, **_do the links to UltiCa need to be direct or are reference chains from one markdown table to another ok, too?_**

Illustrated again, this is what I mean:

image

This is a lot more realistic to manage in practice and also makes it much clearer to actually follow the links. **If 5 doesn't apply, but the rest does**, I can also point the markdown links of the tilesheets directly to the original sprites instead. In that case, since all original sprites are referenced in the tables anyway, **_is the commit edit method still necessary?_** Either way, this is again not a big deal in this configuration, the difference would just be whether I copy one or many reference table rows for the tile sheets.

In any case, thank you for your time and patience in dealing with my tileset's "special needs"!

**Comment by I-am-Erk** [comment]
I'm going to step in here from a straight moderation standpoint. I have not reviewed this whole discussion, but I want to raise a concern: there are some huge, hard to understand information dumps here and it's really difficult to assess this conversation. I'd strongly recommend trying to summarize your questions a bit.

From my perspective, as one of the people who most stands to get in legal trouble if attribution is lost, any question that has to be asked with so many diagrams and images is *probably* going to have "no" as an answer. I know it's a huge pain in the ass but if you're editing and moving an image around, it has to be *easy* to find out who made it and where it came from. If anything blurs that, I could conceivably be dealing with DMCA takedowns and similar fun, and so I have very limited patience to read long discussions about what might be okay.

Does that make sense? I know it sounds harsh and can mean a lot of extra work, but the reality is that the punishments to which I, personally, can be subjected as repo owner are also harsh. I have no room to debate and discuss.

**Comment by Inzarcon** [comment]
That does make perfect sense and doesn't sound harsh at all. And ironically you did identify the core problem of fitting this complicated tileset into proper attribution. Hence the escalating explanations, which did start as simple Discord messages.

A heavily composite tileset such as this may unfortunately simply be inherently incompatible then. Or rather: The extra work required to track the increasing number of relations would far outweigh the time saved by downscaling existing sprites, which defeats the point of doing that in the first place.

Given I've been stumbling from one blunder into another until causing shit to hit the fan, I'll take the hint and close this PR for the time being. Instead I'll try again whenever I'm done creating everything from scratch. And hopefully give a better second impression than the first one I blew here.

**Comment by I-am-Erk** [comment]
You make a good first impression just by doing stuff, I have no hard feelings. I like seeing people contributing. It's just that attribution is easy to mess up and if it does, I stand to potentially be in a lot of trouble, so I can't be flexible about it.

**Pull request closed without merging**
