### PR TITLE
Replacing dirt backgrounds with grass

### PR DESCRIPTION
**Pull request by int-ua**
grass

Fixes: #377 (screenshot is outdated)

### CODE REVIEW

**Comment by int-ua** [comment]
removed dirt from grass
grass

**Comment by I-am-Erk** [comment]
How does this look around pavement or a building?

**Comment by int-ua** [comment]
Will add new screenshots in 5 minutes

**Comment by int-ua** [comment]
https://discord.com/channels/552510581161066497/552510581782085654/793624416655114300

**Pull request merged**
