### PR TITLE
Sprites for shadows, running, and bashing

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Assigns sprites for z-level shadows and running / bashing animations

#### Content of the change
Z-level shadows were added in https://github.com/CleverRaven/Cataclysm-DDA/pull/66730
A few tilesets already have their own shadow sprites so I reused them.  Made new sprites for the rest.  My sprites are made with Krita 5.1 and saved with default settings.

Running and smashing animations were added in https://github.com/CleverRaven/Cataclysm-DDA/pull/65622
I reused the `animation_hit` sprite as `bash_effective` and `fd_smoke` as both `bash_complete` and run_*.  If a tileset lacks these sprites then nothing will be added.

#### Testing
Tilesets compiled successfully.  Tested shadows, running and bashing for each modified tileset.

Shadows (UltiCa)

Bashing (MSX+)

Running (BrownLikeBears)

### CODE REVIEW

**Comment by Fris0uman** [comment]
I'm afraid using smoke for running is going to be confusing. Right now smoke is something you need to pay attention to and avoid, it's a bad idea to reuse a sprite of a danger for something cosmetic

**Comment by Rewryte** [comment]
Alright, I'll glance through the sprite sheets to see if anything else catches my eye but I'll probably just remove the run animation if I can't find anything.  If you have any suggestions, feel free to share them.

We cool with `fd_smoke` as `bash_complete`?

**Comment by Fris0uman** [comment]
> We cool with fd_smoke as bash_complete?

No, it's the same issue, using the srpite for something dangerous for something that is not

**Comment by Rewryte** [comment]
> No, it's the same issue, using the srpite for something dangerous for something that is not

Ok.  Got rid of that as well.

Also changed `bash_effective` to use glass crack sprites if exists.

**Pull request merged**
