### PR TITLE
[ASCII Overmap] Updates to the latest

### PR DESCRIPTION
**Pull request by pedestrian4**
#### Summary
Updates to the latest version

#### Content of the change

More than 100 overmap tiles added since 0.G

### CODE REVIEW

**Comment by Fris0uman** [comment]
What convention are you using to name the glyphes?

**Comment by pedestrian4** [comment]
I used the character's color and extended ascii code number (like black179). the older ones were already ramdomly chosen I want to change it though.

**Comment by pedestrian4** [comment]
> What convention are you using to name the glyphes?

I used the character's color and extended ascii code number (like black179). the older ones were already ramdomly chosen I want to change it though.

**Comment by Fris0uman** [comment]
you can if you want to, but I don't think it's necessary to change the already existign names

**Pull request merged**
