### PR TITLE
more artifacts, tr_portal

### PR DESCRIPTION
**Pull request by int-ua**

### CODE REVIEW

**Comment by int-ua** [comment]
I know beads are huge and not good. But moving only them to unfinished seems too tedious so I'll leave them here, ok?

**Comment by int-ua** [comment]
No hard feelings about the portal, can move it to the unfinished or revert.

**Comment by I-am-Erk** [comment]
I am not sure if items support multiple sprites, you may want to test that.

**Comment by int-ua** [comment]
Ok, a bit later. Meanwhile you can select which ones should be culled.

**Comment by int-ua** [comment]
Ok, looks like it's not supported for items, which ones should I delete?

**Comment by I-am-Erk** [comment]
For now I would keep gamma2

**Pull request merged**
