### PR TITLE
Retro new monsters

### PR DESCRIPTION
**Pull request by Golfavel**
#### Summary
RetroDays "Retrofied commit #1361"

#### Content of the change
Adds RetroDays equivalent sprites and changes from #1361.

#### Testing
Before:
ancient
After:
retrod

#### Additional information
The variant and animation features of the "memory" and "shifting mass" creatures were removed.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Thios PR also edits Neodays, is that normal?

**Comment by Golfavel** [comment]
> Thios PR also edits Neodays, is that normal?

Yeah, it's the exact same commit history as #1361, excluding the last one which is where the RetroDays additions come in. I just branched off from that original branch; I'll look into how to handle it better next time.
```
$git diff --compact-summary neo_new_monsters retro_new_monsters 
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_absence.png (new)                       | Bin 0 -> 290 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_antlion_giant.png (new)                 | Bin 0 -> 302 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_antlion_larva.png (new)                 | Bin 0 -> 292 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_aphid.png (new)                         | Bin 0 -> 294 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_aphid_small.png (new)                   | Bin 0 -> 288 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_bluejay.png (new)                       | Bin 0 -> 316 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_crow_0.json                             |   2 +-
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_grasshopper_giant.png (new)             | Bin 0 -> 300 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_grasshopper_small.png (new)             | Bin 0 -> 285 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_lab_rat.json (new)                      |   1 +
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_lab_rat.png (new)                       | Bin 0 -> 294 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_memory.png (new)                        | Bin 0 -> 284 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_pigeon.png (new)                        | Bin 0 -> 302 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_robin_0.json                            |   2 +-
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_secubot_america.png (new)               | Bin 0 -> 323 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_shifting_mass.png (new)                 | Bin 0 -> 294 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_tadpole.png (new)                       | Bin 0 -> 284 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_wasp_mega.png (new)                     | Bin 0 -> 307 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/{2604_mon_zombear_0.png => mon_zombear.png} | Bin
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zombear_0.json (gone)                   |   1 -
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zombear_acidic.png (new)                | Bin 0 -> 297 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zombear_skeleton.png (new)              | Bin 0 -> 297 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zombeaver.png (new)                     | Bin 0 -> 291 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zombie_horse.png (new)                  | Bin 0 -> 320 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zoose_thorny.png (new)                  | Bin 0 -> 312 bytes
 gfx/Retrodays/pngs_tiles_10x10/monster/mon_zow.png (new)                           | Bin 0 -> 298 bytes
 26 files changed, 3 insertions(+), 3 deletions(-)
```
(git diff for confirmation)

**Comment by Fris0uman** [comment]
Can you rebase this branch on current master then

**Comment by Golfavel** [comment]
Can do.

**Pull request closed without merging**
