### PR TITLE
RetroDays+ Clothes Sprites - RafaelKB

### PR DESCRIPTION
**Pull request by nphyx**
Comprehensive clothing sprites for RetroDays+ courtesy of RafaelKB.

I didn't do anything other than write a script to generate the JSONs and do a quick check in game to verify they were working.

Also this is going to be blocked in the main repo until someone can get the [hats done by Wokko1](https://github.com/CleverRaven/Cataclysm-DDA/pull/40367) into the base set here, or manually merge the `tile_config.json` and the new hat sprites.

Preview:

Screenshot from 2020-05-12 04-00-36

### CODE REVIEW

**Comment by rafaelkb** [comment]
Nice

**Comment by nphyx** [comment]
Per RafaelKB's request, making this a draft while they review some of the sprites. Will update the PR when changes are ready :)

**Comment by nphyx** [comment]
> Also this is going to be blocked in the main repo until someone can get the [hats done by Wokko1](https://github.com/CleverRaven/Cataclysm-DDA/pull/40367) into the base set here, or manually merge the `tile_config.json` and the new hat sprites.

This is fixed in #136

**Comment by barsoosayque** [comment]
Any updates ? 🙂

**Comment by rafaelkb** [comment]
We are going to commit it soon

**Comment by int-ua** [comment]
Was this obsoleted by #318 ?

**Comment by Fris0uman** [comment]
So #318 has the more recent version of sprites made by RafaelKB but it was not tested in game either so it's also stuck as a draft for now. So I htink it is obsolete now, especially since the Retrodays+ folder was renamed since this was opened the merge conflict might be a pain to solve

**Pull request closed without merging**
