### PR TITLE
Neodays stuff.

### PR DESCRIPTION
**Pull request by rafaelkb**
some minor corrections on Neodays, speacially that black strokes that leak into other tiles.

### CODE REVIEW

**Comment by Fris0uman** [comment]
please add some screenshot and split this into smaller PRs, reviewing hundreds of sprites in one go is a huge pain.

**Comment by rafaelkb** [comment]
> please add some screenshot and split this into smaller PRs, reviewing hundreds of sprites in one go is a huge pain.

im sorry, ill do it next time

**Comment by Fris0uman** [comment]
Closing as it can't be reviewed in this state. Please split it over several smaller PRs.

**Pull request closed without merging**
