### PR TITLE
Tools: Preview generation

### PR DESCRIPTION
**Pull request by barsoosayque**
Making items/monsters/overlays previews is so time-consuming, so I decided to write a small script to automate this process.

The script consumes a list of ids to preview, builds a database of items/overlays/monsters in the tileset, then merges them together. I tried to take into account all corner cases that I thought of, so the script is somewhat heavy because it reads JSON definitions (which may be arrays) to search for a sprite.

Nice features:
- If there are multiple sprites for one id, preview them all;
- Combine items/monsters/overlays together in one output image;
- Select skin gender for overlays (*--gender {male,female}*);
- Select skin color for overlays (*--skin {brown,dark,light,rose,tan}*)
- Scale output image (*--scale 4*)
- Custom grid size (actually, only grid width, since the height is calculated)

## Example

<details>

1. ```
    $ ./generate_preview.py  -i ../gfx --overlay-skin brown \
     --overlays-with-items hat_cotton jeans pants
    ```
    ![output](https://user-images.githubusercontent.com/33784900/68453578-83b75900-0228-11ea-955d-5f6889edc0a2.png)


2. ```
    $ ./generate_preview.py -i ../gfx --items pot pot pot pot pot \
    pot pot pot pot pot pot pot pot pot pot pot pot pot
    ```
    output

3. ```
    $ ./generate_preview.py -i ../gfx --monsters mon_pig --items 2x4
    ```
    ![output](https://user-images.githubusercontent.com/33784900/68471542-05bb7800-0251-11ea-8400-2b660f5021c2.png)



</details>

### CODE REVIEW

**Comment by barsoosayque** [comment]
Oh, wait. I just realized that this code can also be used to generate previews for items (without overlay) and monsters (and all in one output), just need to add a few lines.

I will add this, so please, do not merge yet.

**Comment by I-am-Erk** [comment]
Is it ready now?

**Comment by barsoosayque** [comment]
Not yet, I need to fix sprites merging when they are different sizes.

**Comment by barsoosayque** [comment]
Alright ! It's good to go :tada:

**Pull request merged**
