### PR TITLE
Mutant, batteries, wall wiring, EOD and Feline suit sprites

### PR DESCRIPTION
**Pull request by Paprika-H**
This is a test so apologies

#### Summary
Ultica "wall wiring texture"

#### Content of the change

Spirtes
#### Testing
 this is the testing

### CODE REVIEW

**Comment by Fris0uman** [comment]
When json is just setting id and fg to the same thing you don't need the json entry and can just name the png file with the id of the thing it represents

**Comment by Paprika-H** [comment]
> When json is just setting id and fg to the same thing you don't need the json entry and can just name the png file with the id of the thing it represents

Alright, thank you

**Comment by Fris0uman** [comment]
can you include a screenshot of the things showwing up in game once you're done?

**Comment by Paprika-H** [comment]
> can you include a screenshot of the things showwing up in game once you're done?

Will do!

**Comment by Fris0uman** [comment]
Don't put everything in the same PR, if you just want to use it to compose stuff you should open the test pr on your own fork

**Comment by Paprika-H** [comment]
image


> Collaborator

Alright, I got it all done! Apologies for having it all in one PR, I got very carried away

**Pull request merged**
