### PR TITLE
empty PNG for hot air

### PR DESCRIPTION
**Pull request by int-ua**
May fix https://github.com/CleverRaven/Cataclysm-DDA/issues/44042

### CODE REVIEW

**Comment by I-am-Erk** [comment]
Call the PNG "transparent", we're likely to want it for other fields

**Comment by int-ua** [comment]
Do we still need it when it was fixed upstream? I'm inclined to close this PR unless you want these in.

**Comment by int-ua** [comment]
Should I move it to some more generic directory?

**Comment by I-am-Erk** [comment]
we may need to revisit this some day but for now let's not worry about it

**Pull request closed without merging**
