### PR TITLE
add box_cigarette

### PR DESCRIPTION
**Pull request by snipercup**
image

### CODE REVIEW

**Comment by barsoosayque** [comment]
This requires a black bottom outline.

**Comment by snipercup** [comment]
I guess I should mention the artist name: Whaley the Halloween Apparition
Any changes to the sprite should be communicated to Whaley the Halloween Apparition

**Comment by I-am-Erk** [comment]
Can you please put this one in the pngs_incomplete_32x32 folder?

**Comment by snipercup** [comment]
Changed to incomplete

**Pull request merged**
