### PR TITLE
Easy to use, self-contained tileset update script

### PR DESCRIPTION
**Pull request by mlange-42**
#### Summary

Easy to use, self-contained tileset update script

#### Content of the change

Rework `updtset.cmd` and add helper scripts to artists can set up their environment and run updates without needing to touch the command line.

Further, it is not necessary anymore to modify `updtset.cmd` for the local setup. Once environment variable `CDDA_PATH` is set, it should just work out ofthe box with double click. A helper for setting up the variable is also provided.

* [x] Use environment variables `CDDA_PATH` for the game path, and `CDDA_TILESET` for the tileset to be updated
* [x] Add two helper scripts to set these variables interactively
* [x] Modify `updtset.cmd` to let users select game path and tileset interactively if
  * not available as as environment variable (both), and
  * not given as script parameter (tileset)
* [x] ~~Move `compose.py` from the CDDA main repo into this repo, folder `tools`~~
  * ~~(required as the pre-compiled game does not contain that file)~~
* [x] Add a script to set environment variable `LIBVIPS_PATH`
* [x] Modify `compose.py` in the main game repo to include `LIBVIPS_PATH` into library search path (see https://github.com/CleverRaven/Cataclysm-DDA/pull/60923)
* [x] ~~Include `compose.py` from the main game repo into binary distributions~~
* [x] Add a copy of `compose.py` to folder `tools`
* [x] Document the new workflow for setting up (see [doc/installation_windows.md](https://github.com/I-am-Erk/CDDA-Tilesets/blob/33430ef/doc/installation_windows.md))

#### Testing

Tried it out in it's different variations.

#### Additional information

Usage without touching Command line, fixed tileset:

1. Drag&drop game directory onto `set_game_path.cmd`
2. Drag&drop `libvips` directory onto `set_vips_path.cmd`
3. Double click `set_tileset.cmd`, and choose one of the presented options
4. Double click `updtset.cmd`, should work without a hassle

Usage without touching Command line, flexible tileset:

1. Drag&drop game directory onto `set_game_path.cmd`
2. Drag&drop `libvips` directory onto `set_vips_path.cmd`
3. Double click `updtset.cmd`, and choose one of the presented tileset options

> Note: Requires inclusion of `compose.py` from the main game repo into binary distributions, in order to make it work out of the box for artists that work with precompiled binaries.

### CODE REVIEW

**Comment by Fris0uman** [comment]
The issue with moving compose.py here is that it's going to desync with the one in the main repo

**Comment by mlange-42** [comment]
> The issue with moving compose.py here is that it's going to desync with the one in the main repo

Yeah, I am aware that this is not an easy decision. Moving instead of copying would avoid desync. But I start to think that the main repo *is* the right place for the script.

So maybe a solution would be to include `compose.py` in the game distribution. `updtset.cmd` could use the script from the game directory then, and it would also work for users that downloaded a build instead of cloning the repo.

What do you think?

**Comment by Fris0uman** [comment]
Users could get it by going to https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py and copy/pasting it into a new file

**Comment by mlange-42** [comment]
> Users could get it by going to https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py and copy/pasting it into a new file

In addition to making usage as easy as possible, one of the aims of this PR is to get rid of the necessity to make changes the repo(s) just to get it set up. Firstly, this is one more step to set up, secondly it clutters the repo's working copy and users have to constantly take care to not accidentially commit `compose.py` (or currently their changes to `updtset.cmd`).

Are there any reasons not to include it into the distribution?

**Comment by vetall812** [comment]
As I talked to some artists unfamiliar with github I think that moving compose.py to tileset directory could be a better solution. As it will avoid some ...lets say "difficult" steps to set up and maintain infrastructure. There may be some reasons to keep it in main repository. But it is a script that work with tilesets.

**Comment by mlange-42** [comment]
Have to withdraw my own argument...

> Moving instead of copying would avoid desync.

@Fris0uman probably referred to new game features that need edits to the script, which would then be in another repo/PR.

**Comment by mlange-42** [comment]
Reworked to work with the script in the game directory instead of moving the script here. Requires inclusion of the script in binary distributions. Will make a PR in the game repo for it.

**Comment by Fris0uman** [comment]
> users have to constantly take care to not accidentially commit compose.py (or currently their changes to updtset.cmd).
We could add to gitignore. The script is small enough that putting it in the game is not an issue but it really doesn't make sense. Trying to make it easier to contribute art is a great idea, but asking people to download one file is really not a hard bar to pass

**Comment by mlange-42** [comment]
> > users have to constantly take care to not accidentially commit compose.py (or currently their changes to updtset.cmd).
> 
> We could add to gitignore. The script is small enough that putting it in the game is not an issue but it really doesn't make sense. Trying to make it easier to contribute art is a great idea, but asking people to download one file is really not a hard bar to pass

Adding it to .gitignore is a good step. However, it would require an additional manual action by the user to get it into sync after a pull or game update. 🤔

**Comment by Fris0uman** [comment]
I guess we can have a copy of compose.py in this repo. It is easier for us to update it than it would be for artists than don't want to touch github

**Comment by mlange-42** [comment]
> I guess we can have a copy of compose.py in this repo. It is easier for us to update it than it would be for artists than don't want to touch github

Not my favorite solution, but changed accordingly.

**Pull request merged**
