### PR TITLE
zweihander

### PR DESCRIPTION
**Pull request by int-ua**

### CODE REVIEW

**Comment by barsoosayque** [comment]
Looks very fantasy to me. And doesn't really resembles a zweihänder in my opinion (including that source 3d model). Proportions are off: grip is too short, blade is too short, the second parrying guard is just enormous. If you can erase the second guard, it might work as a regular longsword.

**Comment by int-ua** [comment]
What does resemble a zweihänder in your opinion? :)
Anyway, I like it as it is, you can either accept it or reject.

**Comment by I-am-Erk** [comment]
It doesn't look too different from historical zweihanders to me

https://en.m.wikipedia.org/wiki/Zweih%C3%A4nder

**Comment by int-ua** [comment]
Oh, I can move it into the incomplete folder, ok?

**Comment by barsoosayque** [comment]
> Oh, I can move it into the incomplete folder, ok?

Yep

**Comment by int-ua** [comment]
done

**Pull request merged**
