### PR TITLE
Fix wrong roof tiles for vp_roof and vp_hdroof

### PR DESCRIPTION
**Pull request by stubkan**
#### Summary
Ultica "Replace vehicle roof sprites"

#### Content of the change

Removed blue (??) and similar png from hoder/filler and removed roof entries from that vehicle.json

Inserted 2 good pngs in vehicle/incomplete32x32/board
Added vehicle roof entries to the json there

#### Testing

image

image

#### Additional information

It is safe to merge this, even without the roof fix merged in the main game.  It has no gameplay effect, no memory usage effect (there was that weird blue png already)

And will be good for the day that the roof visibility toggle pr comes into effect.

### CODE REVIEW

**Comment by Fris0uman** [comment]
You forgot to remove/replace at leat one mention of  `1767_vp_hdroof_0` from somwhere

**Comment by stubkan** [comment]
I think I got it now

**Comment by Fris0uman** [comment]
Can you move the roof sprites and accompanying json to `CDDA-Tilesets/scratch/UltimateCataclysm/vehicles/`?
So we have it for when roofs are displayed but it won't get into the tilesheet prematurly

**Comment by Fris0uman** [comment]
Closing to clear the queu, feel free to reopen and finish

**Pull request closed without merging**
