### PR TITLE
[MSX] Add attribution to big dino sprites

### PR DESCRIPTION
**Pull request by Fris0uman**
Turns out that the big dino have been imported from some unknown japanese comunity version of MSX. So as a safe measure I'm just removing them.

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
These seem to be community-made tiles, I have found these tiles nowhere apart from the forums, gonna research some more and see if I can find anything.

**Comment by Theawesomeboophis** [comment]
It seems that the creator of the post on the Xotto forums added these tiles the day before the post was posted, they might come from him, if he's still active, we can probably ask him.

**Comment by Theawesomeboophis** [comment]
It seems that these tiles come directly from Japanese Wiki, cannot confirm this however, because I cannot open the pngs on the wiki for some reason.

**Comment by Theawesomeboophis** [comment]
I have reverse image searched it, and out of 44.5 billion photos, no results were found, it seems these are original tiles.

**Comment by anothersimulacrum** [comment]
I'm not particularly confident in that as a test for provenance of tiles.

**Comment by Theawesomeboophis** [comment]
> I'm not particularly confident in that as a test for provenance of tiles.
Nor am I, the Japanese Wiki is the most possible source, but cannot be confirmed.

**Comment by anothersimulacrum** [comment]
In that case, the art was recognized as coming from a minecraft mod by someone using the tileset.

**Comment by Theawesomeboophis** [comment]
I believe the origin of these is a deleted Japanese Wiki article based on
clues I have found, but there is no way to prove this as I believe the page
was deleted.

**Comment by Theawesomeboophis** [comment]
Is Budg3 still active, because if so, we could ask him where he found the
tiles originally.

**Comment by Theawesomeboophis** [comment]
I believe the page may have been deleted during the transition of the
Japanese wiki from a place for tileset and mod downloads to being more like
the English wiki.

**Comment by Fris0uman** [comment]
> I'm not particularly confident in that as a test for provenance of tiles.

What do you mean? The sprite could be legit sure, but we don't know and I don't see a way to check so removing them seems like the safe bet.

**Comment by Theawesomeboophis** [comment]
I agree, I was merely trying to find out possible places they may have come
from if they are original, and the earliest instance of these sprites that
I can find is May 17, 2018, but according to Budg3's original post on May
18, 2018, they came from the Japanese community, which is why I believe
they came from the Japanese wiki originally, however, if they did come from
Japanese Wiki, we still don't know where Japanese wiki got them from, which
brings us back to where we began, since the page is possibly deleted as
well as the fact that we still have no way to confirm the authenticity of
these tiles, The trail stops on May 17 and there's no way to know where
they came from before that.

**Comment by anothersimulacrum** [comment]
> > I'm not particularly confident in that as a test for provenance of tiles.
> 
> What do you mean? The sprite could be legit sure, but we don't know and I don't see a way to check so removing them seems like the safe bet.

I was responding to comments from Theawesomeboophis which appear to have since been deleted.

**Comment by Theawesomeboophis** [comment]
> > > I'm not particularly confident in that as a test for provenance of tiles.
> > 
> > 
> > What do you mean? The sprite could be legit sure, but we don't know and I don't see a way to check so removing them seems like the safe bet.
> 
> I was responding to comments from Theawesomeboophis which appear to have since been deleted.

They were deleted because I couldn't find original source, and all trails led to dead ends.

**Comment by Theawesomeboophis** [comment]
Good news, I am closer to finding the origin of these tiles, I found the old Japanese Xotto on the wiki and it mentions trees.png, the file that these sprites come from as being added on 2017/2/16, which is the earliest mention of these sprites so far.

**Comment by Theawesomeboophis** [comment]
treeO
tree
Found them.

**Comment by Theawesomeboophis** [comment]
I have put together the timeline of these sprites so far.
Unknown time before May 9, 2018: Sprites added to Japanese Xotto
May 9, 2018: Budg3 post about sprites on forums
May 17, 2018: Sprites added to Budg3's version of xotto
May 27, 2018: Japanese Xotto updates, coinciding with the release of the English Patch 11.

**Comment by Theawesomeboophis** [comment]
Triceratops
https://commons.wikimedia.org/wiki/Triceratops#/media/File:Triceratops0225c.jpg

Stegosaurus
https://commons.wikimedia.org/wiki/Stegosaurus#/media/File:Ba%C5%82t%C3%B3w_Park_Jurajski_001.jpg

Ankylosaurus
https://commons.wikimedia.org/wiki/Category:Ankylosaurus_life_restorations#/media/File:Ankylosaurus,_Wild_Adventures.JPG

Allosaurus
https://commons.wikimedia.org/wiki/Allosaurus#/media/File:Allosaurus_in_Baltow_20060916_1500_white_background.jpg

Parasaurolophus
https://commons.wikimedia.org/wiki/Category:Parasaurolophus_life_restorations#/media/File:Parasaurolophus,_Wild_Adventures.JPG

Utahraptor
https://commons.wikimedia.org/wiki/Category:Utahraptor_life_restorations#/media/File:Baltow_JuraPark_utahraptor_ostrommaysorum_01.jpg
Origins found, taken directly from Japanese Xotto Patch 7

**Comment by Theawesomeboophis** [comment]
[dinosaur_credit.txt](https://github.com/I-am-Erk/CDDA-Tilesets/files/5562225/dinosaur_credit.txt)
Taken directly from download.

**Comment by Theawesomeboophis** [comment]
trees.png edited 7/24/2017, which is the earliest instance of these sprites and the date they were added.

**Comment by Theawesomeboophis** [comment]
It took me a while to find this, but I have finally found the source of these sprites, however, due to noticeable differences between actual pictures and sprites, I believe these are indeed original sprites, although they are inspired by above pictures, they are not exact digitizations of said pictures.

**Comment by Theawesomeboophis** [comment]
Look at animatronics mod sprites from Undead People and Xotto to see what I mean, those sprites are clearly downsized versions of the original pictures, these are not, meaning they were created based upon the above pictures, but they are not just downsized versions of said images, meaning these sprites are recreations of the pictures in a pixelated manor, rather than just being the pictures themselves.

**Comment by Theawesomeboophis** [comment]
There are also noticeable color differences between the stegosaurus image and sprite, which would not be possible if it was the same image in a downsized form, if that was the case, they would be the exact same color, which their not.

**Comment by Theawesomeboophis** [comment]
All sprites not accounted for through those links( such as T-rex) I assume to be either inspired by other pictures or completely original.

**Comment by Theawesomeboophis** [comment]
Triceratops0225c
5466_mon_triceratops_0
I reduced actual image of triceratops down to pixel size. As you can see, they look very different.

**Comment by Theawesomeboophis** [comment]
It seems that all of these images( Of which these sprites are based upon) are from statues from a Polish dinosaur theme park called Jura Park, with the exception of triceratops, which is a life restoration done with CGI.

**Comment by Theawesomeboophis** [comment]
Utah raptor statue from Jura Park.

**Comment by Theawesomeboophis** [comment]
The Last statue is from Wild Adventures( another theme park)'s Jurassic Park River Adventure( probably shut down due to name similarities with the movie and fears of copyright), which was recently reopened.

Original Statue of Parasaurolophus.

**Comment by Theawesomeboophis** [comment]
Anklyosaurus is incorrectly linked as coming from Wild Adventures, when in actuality, Anklyosaurus statue is also from Jura Park.
_-_JuraPark_Baltow_(1).JPG)
Anklyosaurus statue that sprite is based upon.

**Comment by Fris0uman** [comment]
Do you have an idea of who did the convertion from the wiki images to the sprites?

**Comment by Theawesomeboophis** [comment]
The same guy who made Japanese Xotto Patch 7, not sure name, I can check
Japanese wiki if you want.

**Comment by Fris0uman** [comment]
Yes it would be very helpfull. Basically If I get an author name I'll just add atrribution to the sprites and we'll keep them in the set

**Comment by Theawesomeboophis** [comment]
Ok, will do. Glad we finally found a source, might want to add creators of
original images as well.

Yes it would be very helpfull. Basically If I get an author name I'll just
add atrribution to the sprites and we'll keep them in the set

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/I-am-Erk/CDDA-Tilesets/pull/308#issuecomment-733173836>,
or unsubscribe

**Comment by Theawesomeboophis** [comment]
The creators name appears to be Kari but It seems to be anonymous, but
tileset is called Xotto Patch 11 Kari which is what gave me this conclusion.

**Comment by Theawesomeboophis** [comment]
Looking at files to see if there's another name in jsons.

**Comment by Theawesomeboophis** [comment]
Nothing in files, but the name of zip file has Kari at the end, which I
assume to be their name.

**Comment by Theawesomeboophis** [comment]
Wikimedia post have all creators credited as well, just in case we need
those.

**Comment by Theawesomeboophis** [comment]
Patch 7 Kari btw, not 11, my mistake.

**Pull request merged**
