### PR TITLE
[Larwick] Backrooms

### PR DESCRIPTION
**Pull request by Golfavel**
#### Summary
Adds backrooms overmap sprites

#### Content of the change
Adds: backrooms floor

#### Testing
_Before_
lar_vanbef
_After_
lar_vanaft

### CODE REVIEW

**Comment by Fris0uman** [comment]
Isn't this pretty unconfortable to look at? I'm not sure making the hwole screen bright yellow is a good idea

**Comment by Golfavel** [comment]
The overmap has no use with the backrooms mod and the predominant color is yellow (albeit not as vibrant). I can change it if it's considered necessary.

**Comment by Fris0uman** [comment]
Yes change it for something less agressive

**Comment by Golfavel** [comment]
Done.

**Pull request merged**
