### PR TITLE
[Ultica] Yet another grass rework

### PR DESCRIPTION
**Pull request by barsoosayque**
image
image
image

### CODE REVIEW

**Comment by int-ua** [comment]
> wget: bad address 'raw.githubusercontent.com'

0_o

**Comment by int-ua** [comment]
Moss on the third screenshot looks different for some reason, what season is it?

**Comment by acepleiades** [comment]
This is really great stuff

**Comment by acepleiades** [comment]
> Moss on the third screenshot looks different for some reason, what season is it?

Autumn

**Pull request merged**
