### PR TITLE
[MD] added water grass tiles

### PR DESCRIPTION
**Pull request by AlbertTheTerrible**
#### Summary
MD "water tiles and grass tiles added"

#### Content of the change
Added water_sh (still wip)
Corrected color on grass
Added t_pavement and several variants
added t_pavement_y
More to come

### CODE REVIEW

**Comment by AlbertTheTerrible** [comment]
i have literally copied the summary from my other post, just edited the content and i still can't get it to validate lol

**Comment by AlbertTheTerrible** [comment]
Oh wait there's actually another error

**Comment by AlbertTheTerrible** [comment]
finally got a PR with no errors, yay

**Comment by AlbertTheTerrible** [comment]
I think i made a mistake, this should have been a branch of the other branch i made, instead i made a branch of master again, i'm gonna ask to finish this PR and close it because i already noticed i've been messing things up on my side. I'll keep adding the remaining of my stuff on a new one and hopefully on a proper branch, i'm really sorry about this. If everything is already i'll have this PR as done and ready to merge

**Comment by Fris0uman** [comment]
Branching of master is the right thing to do though

**Comment by Fris0uman** [comment]
Looks like you removed the autotile for both grass and pavement, is that intended?

**Comment by AlbertTheTerrible** [comment]
Good eye fris. The only png i deleted was the old big grass autotile.The one with too many tiles. The one in there was the old one with the wrong colors and the first scribbles i had made in pixel art. But i'm pretty sure i had deleted that on the other PR, not this one. I intended to add this updated version but i'm waiting for the PR to merge so i can work from a single PR and not from various PRs with new and old art mixed in, to avoid more confusion

The issues i mentioned in my comment above are due to that. I thought you could make PRs of PRs, at least it would be less confusing to me

**Comment by AlbertTheTerrible** [comment]
Here's the grass sprites i mentioned

image

**Comment by AlbertTheTerrible** [comment]
I was here looking for the pavement autotile and it's right there in the autotile folder

image

**Comment by AlbertTheTerrible** [comment]
If we could get both of the PRs merged so i don't have 2 open with old and new sprites going on that'd be great. 

I'm gonna work on a single PR from now on and when you guys feel like it's too big just merge it away. I think it's better to me that way

**Comment by Fris0uman** [comment]
Okay, looks almost ready to merge: can you just use this http://dev.narc.ro/cataclysm/format.html to format your two json files?

**Comment by AlbertTheTerrible** [comment]
Aaah, forgot about that. I already am using that, it's just that with all the edits i do it loses format. Just a second

**Comment by AlbertTheTerrible** [comment]
Done. It was just 2 jsons correct? If so then they are ready

**Comment by Fris0uman** [comment]
Looks good to me. Congrats on your first completed PR ^^

**Pull request merged**
